Honor show all sources setting
elementary/wingpanel-indicator-keyboard pull request #83
Opened 2020-11-24 18:31 UTC by jeremypw

Shows the input source even if there is only one if the corresponding setting is true.  This allows convenient access to keyboard settings and layout if desired.

Note this does not fix the issue with not showing ibus input methods, which will be tackled in another PR.

2020-11-25 01:27 UTC, danrabbit commented
Hm, I'm not sure the key description matches what this does: "Makes all installed input sources available for choosing in System Settings". This seems to imply that in GNOME Settings some input sources are hidden. I don't think this is intended to affect the panel.

It would probably be better to ship our own key for this setting that is explicitly meant for this purpose

2020-11-25 16:14 UTC, jeremypw commented
OK, if you agree this is a worthwhile thing then I can add our own setting.

2020-11-26 19:47 UTC, jeremypw commented
Now added our own setting, with default set to show even one layout (to be advised).

2020-12-01 22:24 UTC, danrabbit requested changes
Left a few comments. This doesn't appear to update when I change the setting in dconf

2020-12-01 22:24 UTC, danrabbit commented on src/LayoutsManager.vala
> +        settings.changed["show-all-sources"].connect_after (() => {
Is this still relevant?

2020-12-01 22:24 UTC, danrabbit commented on data/keyboard.gschema.xml
> +      <default>true</default>
This should probably default to false since I imagine most people don't need to disambiguate. Thoughts @cassidyjames?

2020-12-01 22:24 UTC, danrabbit commented on src/LayoutsManager.vala
> +        });
This seems a little convoluted. It would probably be simpler to either make the settings object static and reference it directly from here or just instantiate a new GLib.Settings here

2020-12-02 11:23 UTC, jeremypw commented on data/keyboard.gschema.xml
> +      <default>true</default>
OK.  I was just thinking it might be convenient to expose some keyboard settings here (or in the case of a single ibus engine expose input modes), but this can be revisited if necessary. Reverting to false for now to match current behaviour.

2020-12-02 12:20 UTC, jeremypw commented on src/LayoutsManager.vala
> +        });
Thanks, I have refactored this to avoid a new property for LayoutManager altogether and control everything from Indicator in the same way as for the CapsLock and Numlock visibility

2020-12-02 12:29 UTC, jeremypw commented
Changes with dconf no reflected in UI

2020-12-02 19:54 UTC, danrabbit approved these changes
Looks good and works as expected. Nice job!

2020-12-02 19:54 UTC, merged