Tooltip Indicator
elementary/wingpanel-indicator-keyboard pull request #87
Opened 2020-12-03 03:03 UTC by andirsun

close : #84

2020-12-05 16:33 UTC, andirsun commented
I just improve the message as the same behavior in greeter. 
Case 1 : "Num Lock is on"
Case 2 : "Caps Lock is on"
Case 3 : "Caps Lock &amp; Num Lock are on"
![deepin-screen-recorder_Select area_20201205113109](https://user-images.githubusercontent.com/22928302/101256596-6d125880-36ed-11eb-8371-7e700b155d69.gif)

2020-12-05 17:42 UTC, meisenzahl requested changes
I suggested some changes to make the texts translatable.

2020-12-05 17:42 UTC, meisenzahl commented on src/Indicator.vala
> +            message = "Caps Lock &amp; Num Lock are on";
```suggestion
            message = _("Caps Lock &amp; Num Lock are on");
```

2020-12-05 17:42 UTC, meisenzahl commented on src/Indicator.vala
> +            message = "Num Lock is on";
```suggestion
            message = _("Num Lock is on");
```

2020-12-05 17:42 UTC, meisenzahl commented on src/Indicator.vala
> +            message = "Caps Lock is on";
```suggestion
            message = _("Caps Lock is on");
```

2020-12-06 07:56 UTC, meisenzahl reviewed
LGTM but lets wait for review of @elementary/ux

2020-12-06 20:27 UTC, cassidyjames requested changes
Can we have different tooltips per icon? It would make it more clear what each indicator is showing. Then we would just have “Num Lock is on” for the numlock icon, and “Caps Lock is on” for the Caps Lock icon. No need to say they're off when the icon is not visible.

For the layout icon, the current layout name would make sense to show in a tooltip, but that can be a different PR.

2020-12-07 04:34 UTC, andirsun commented
> Can we have different tooltips per icon? It would make it more clear what each indicator is showing. Then we would just have “Num Lock is on” for the numlock icon, and “Caps Lock is on” for the Caps Lock icon. No need to say they're off when the icon is not visible.
> 
> For the layout icon, the current layout name would make sense to show in a tooltip, but that can be a different PR.

Sure!, I can work on this change tomorrwo

2020-12-09 10:59 UTC, jeremypw commented
On my system the caps lock and numlock revealers seem to operate weirdly.  Sometimes nothing happens - sometimes the wrong revealer activates. Investigating.

2020-12-09 11:00 UTC, jeremypw commented
Sorry - just realised this is only about tooltips!

2020-12-09 11:13 UTC, jeremypw requested changes
Do you need to update the tooltips on visibility change?  When the child is not visible the tooltip does not change and is not visible.  I think they can just be set once as tooltips of the *icons* in the constructor and lose the update_tooltips () functions.

2020-12-09 11:17 UTC, andirsun commented
> Do you need to update the tooltips on visibility change?  When the child is not visible the tooltip does not change and is not visible.  I think they can just be set once as tooltips of the *icons* in the constructor and lose the update_tooltips () functions.

You are right, the tooltips can be setted only in the constructor. Let me do the change.
Thanks for review

2020-12-09 11:54 UTC, jeremypw commented
I think my other problems with these revealers may be due to running in a VirtualBox VM which seems to swallow some keymap state changes.

2020-12-10 09:57 UTC, jeremypw approved these changes
Looks good to me.

2020-12-10 19:33 UTC, cassidyjames approved these changes
Looks good UX-wise as well. Thanks!

2020-12-10 19:33 UTC, merged