Show ibus methods
elementary/wingpanel-indicator-keyboard pull request #96
Opened 2021-02-03 20:21 UTC by jeremypw

Needs https://github.com/elementary/switchboard-plug-keyboard/pull/341  (manual entry of an ibus method into org.gnome.desktop.input-source.sources) to have an effect.

Also requires an issue with Gala KeyboardManager to be fixed to have selected IBus method use the expected keyboard layout.

2021-02-05 10:27 UTC, jeremypw commented
Input source Xkb keyboard (UK English layout);
![Screenshot from 2021-02-05 10 18 01](https://user-images.githubusercontent.com/10513844/107021666-598e7700-679c-11eb-93e8-c661c495ec66.png)

Input source Ibus Mozc Japanese using UK English keyboard layout
![Screenshot from 2021-02-05 10 20 53](https://user-images.githubusercontent.com/10513844/107021667-5abfa400-679c-11eb-91e1-ec1fe2378345.png)

2021-02-14 01:24 UTC, ryonakano commented
> Input source Xkb keyboard (UK English layout);
> ![Screenshot from 2021-02-05 10 18 01](https://user-images.githubusercontent.com/10513844/107021666-598e7700-679c-11eb-93e8-c661c495ec66.png)
> 
> Input source Ibus Mozc Japanese using UK English keyboard layout
> ![Screenshot from 2021-02-05 10 20 53](https://user-images.githubusercontent.com/10513844/107021667-5abfa400-679c-11eb-91e1-ec1fe2378345.png)

It might be a little strange that we can check two radiobuttons here (xkb and ibus engine) :thinking:

2021-02-14 11:59 UTC, jeremypw commented
> It might be a little strange that we can check two radiobuttons here (xkb and ibus engine) :thinking:

How about if there is a separator between the xkb and ibus lists?

2021-02-15 17:29 UTC, jeremypw commented
With separator:
![image](https://user-images.githubusercontent.com/10513844/107977615-4efd8a00-6fb3-11eb-8f52-9a242a61a4c0.png)

2021-02-15 17:33 UTC, jeremypw commented
A couple questions remain:

1) Do we need any headers to indicate what the two lists denote?
2) It is not immediately obbious that to turn off an ibus input method you click on a keyboard layout (even if it is already ticked).  Do we need a "None" entry in the input method list (when input methods are available) or a switch?

2021-03-11 00:22 UTC, danrabbit commented
1. I'm not certain a separator makes things clear on its own here; header labels make sense to me.
2. As long as that works conceptually in terms of how you think about input methods (ie: its clear that Ibus is a service you are enabling or disabling) a switch with the h4 style class could work and also act as the list header. The list of input methods could hide when it's turned off.

2021-03-14 17:12 UTC, jeremypw commented
After latest commits:

![Screenshot from 2021-03-14 17 08 25](https://user-images.githubusercontent.com/10513844/111077367-65caca00-84e8-11eb-84e7-3f4a15756f10.png)

2021-03-14 17:48 UTC, jeremypw commented
The necessary Gala and Greeter fixes have now been merged.

2021-03-17 00:29 UTC, danrabbit requested changes
Just a few comments, but I think this makes sense from a design perspective

2021-03-17 00:29 UTC, danrabbit commented on src/LayoutsManager.vala
> +            margin = 3,
Can we take this out? I think it would be better to set the margins in the stylesheet

2021-03-17 00:29 UTC, danrabbit commented on src/LayoutsManager.vala
> +        xkb_header = new Gtk.Label (_("Keyboard layout")) {
Headers should be title case :)
```suggestion
        xkb_header = new Gtk.Label (_("Keyboard Layout")) {
```

2021-03-17 00:29 UTC, danrabbit commented on src/LayoutButton.vala
> +        button.get_style_context ().add_class (Gtk.STYLE_CLASS_RADIO);
Does this do the same as https://valadoc.org/gtk+-3.0/Gtk.ModelButton.role.html ?

2021-03-17 00:29 UTC, danrabbit commented on src/LayoutsManager.vala
> +        ibus_header_grid.add (ibus_header);
It's a little hard to follow what's going on with things jumbled and no white space:
```suggestion
        var ibus_separator = new Gtk.Separator (Gtk.Orientation.HORIZONTAL);

        ibus_header = new Granite.SwitchModelButton (_("Input Method")) {
            active = true
        };
        ibus_header.get_style_context ().add_class (Granite.STYLE_CLASS_H4_LABEL);

        var ibus_header_grid = new Gtk.Grid () {
            orientation = Gtk.Orientation.VERTICAL
        };
        ibus_header_grid.add (ibus_separator);
        ibus_header_grid.add (ibus_header);
```

2021-03-17 00:29 UTC, danrabbit commented on src/LayoutsManager.vala
> +
double whitespace

2021-03-17 00:29 UTC, danrabbit commented on src/LayoutsManager.vala
> +public class Keyboard.Widgets.LayoutManager : Gtk.ListBox {
Why is this a listbox now?

2021-03-17 12:07 UTC, jeremypw commented on src/LayoutsManager.vala
> +public class Keyboard.Widgets.LayoutManager : Gtk.ListBox {
I think it was partly because that is what other wingpanel indicators use and I thought it would make styling easier. The number of potential entries does not warrant a ScrolledWindow.

2021-03-17 12:08 UTC, jeremypw commented on src/LayoutsManager.vala
> +            margin = 3,
Done

2021-03-17 12:08 UTC, jeremypw commented on src/LayoutsManager.vala
> +        xkb_header = new Gtk.Label (_("Keyboard layout")) {
Done

2021-03-17 12:08 UTC, jeremypw commented on src/LayoutsManager.vala
> +        ibus_header_grid.add (ibus_header);
Done

2021-03-17 12:09 UTC, jeremypw commented on src/LayoutsManager.vala
> +
Fixed

2021-03-17 12:13 UTC, jeremypw commented on src/LayoutButton.vala
> +        button.get_style_context ().add_class (Gtk.STYLE_CLASS_RADIO);
Yes, in fact the appearance is determined from the action automatically so I will take out this line.

2021-03-17 15:01 UTC, danrabbit commented on src/LayoutsManager.vala
> +public class Keyboard.Widgets.LayoutManager : Gtk.ListBox {
As far as I can tell, the only things that get packed here are the revealers for the header and the actual list of options right? So shouldn't this just be a grid?

2021-03-17 18:53 UTC, jeremypw commented
@danrabbit Will you fix the header margin issue in the stylesheet or does something need to be done in this PR?

Based on Gtk.Grid

![Screenshot from 2021-03-17 18 48 46](https://user-images.githubusercontent.com/10513844/111522030-bdb83980-8751-11eb-92e7-4d39da893340.png)

2021-03-17 19:33 UTC, danrabbit commented
Yep I'll take care of that in the system stylesheet :)

2021-03-19 16:54 UTC, danrabbit approved these changes
I'm happy if @ryonakano is happy :)

2021-03-19 17:14 UTC, jeremypw commented
One thing occurred to me - do we need to include code to detect pre-existing ibus input methods which were set up before the new version of the switchboard plug and there not integrated into the `input-sources` setting?  Opening and closing the switchboard keyboard plug is required update the setting.

2021-03-20 17:48 UTC, jeremypw commented
I think it best to merge this now that the corresponding switchboard plug PR is merged, and deal with any upgrade problems later.

2021-03-20 17:48 UTC, merged